version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.3

base_image: &base_image
  resource_class: small
  docker:
    - image: cimg/base:2022.04

go_image: &go_image
  resource_class: medium
  docker:
    - image: cimg/go:1.19

go_node_image: &go_node_image
  resource_class: medium
  docker:
    - image: cimg/go:1.19-node

node_image: &node_image
  resource_class: medium
  docker:
    - image: cimg/node:18.0.0

  setup_build_remote_docker:
    steps:
      - setup_remote_docker:
          version: 20.10.11
          docker_layer_caching: true

jobs:
  build_and_publish:
    <<: *base_image
    environment:
      DOCKER_BUILDKIT: 1
    steps:
      - checkout

workflows:
  version: 2
  build_and_publish:
    jobs:
      - aws-ecr/build-and-push-image:
          assume-web-identity: true
          aws-cli-version: latest
          dockerfile: Dockerfile
          executor: aws-ecr/default
          extra-build-args: '--compress'
          no-output-timeout: 20m
          platform: linux/amd64
          push-image: true
          repo: productcatalogservice
          repo-scan-on-push: true
          role-arn: '${ROLE_ARN}'
          role-session-name: productcatalogservice
          skip-when-tags-exist: true
          tag: '${CIRCLE_SHA1}'
          context: 
            - ecr
